### PR TITLE
Resolve issues when installing the Prisma client in a PNPM workspace using Nuxt layers

### LINKED ISSUE #29: Package manager cannot get resolved when using Nuxt Layers
This is a continuation of #20. I'll provide a summary of the issue:

When using Nuxt layers and Node/PNPM workspaces, no lockfiles will be present in the directory of the Nuxt layer. This causes nuxt-prisma to fall back to `npm`. This becomes a problem when using `pnpm` and its workspaces functionality, since `npm` has no idea what the heck it should do.

I imagine the solution be twofold:
1. Look at the actual project root for the lockfiles
2. Throw a warning when the package manager falls back to `npm`, since something is not right at that point

I have a reproduction repository here: https://github.com/Dobefu/nuxt-prisma-pnpm-workspaces

Also, I intend to write a fix for this, but I'll have some lunch first.
🥪 <- This is what my lunch will look like

### PR DESCRIPTION
**Pull request by Dobefu**
This PR will fix #29

### CODE REVIEW

**Comment by Dobefu** [comment]
Please note: on this version of the PR, installation will happen in the wring Nuxt layer. A workaround for now is to manually install the client and set the `installPrismaClient` option to `false`.
I do not have much time to look into this further for a couple of days, so I hope this is a helpful start at least.

**Comment by Dobefu** [comment]
I'm back!

@ankur-arch I would like to add two configuration options, but I'd like your thoughts on it:

- `packageManager`
  - Will allow users to skip the whole filesystem checks, and is less error-prone
  - This will be optional, and fall back to the current detection method
- `prismaRoot`
  - Will allow users to customise where Prisma does its thing
  - Will resolve #16
  - Will resolve #29
  - Will probably resolve #31

I think especially the second option would benefit a lot of people, since I don't see a way that we can detect it in the code in a reliable and performant manner.

**Comment by ankur-arch** [comment]
Thanks @Dobefu! I'll check on this the next week as I'm on limited availability this week.

**Comment by husayt** [comment]
@ankur-arch will be really nice if this could be checked. Many users of nuxt-prisma are using layers and if already there is a solution to this issue, why not to use it.

**Comment by husayt** [comment]
> @ankur-arch will be really nice if this could be checked. Many users of nuxt-prisma are using layers and if already there is a solution to this issue, why not to use it.

Just to check if the issue I had was related to this and not something else, I switched to npm and it worked. So it was definetely caused by lack of pnpm support. Switching to npm can be a workaround for now

**Comment by ankur-arch** [comment]
Hey @Dobefu 👋,  

This has been in draft for a while, so I wanted to check in to see if you’re planning to get to this. Thanks for your contributions so far—they’ve been really valuable 🔥 !  

Let me know if you’re planning to pick this up; otherwise, I’ll move forward with the updates to ensure compatibility with other package managers and Nuxt layers, as I’d like to proceed soon.  

Looking forward to hearing from you and possibly collaborating again 😄 !

**Comment by Dobefu** [comment]
Hi @ankur-arch!

I'm certainly open to collaborate again!

To be quite honest, I was waiting for your thoughts on https://github.com/prisma/nuxt-prisma/pull/30#issuecomment-2285883863 and then proceeded to... kind of forget to follow up on it 😅. My apologies. What are your thoughts on the configuration options in my previous comment? If they're alright to add, I can look into it this weekend.

**Comment by Dobefu** [comment]
Alrighty, I've fixed the merge conflicts.
I've tested it, and I believe that the PR is pretty much ready to be reviewed.
I'll just assume that the two extra options are fine 🙂

**Comment by Dobefu** [comment]
Hi @ankur-arch,

Have you had time to look into this, yet?
A CI task has failed, but as far as I can see, this might be because of permissions on my end. It shouldn't be related to my changes at all, unless I'm mistaken.

**Comment by ankur-arch** [comment]
Hey @Dobefu 👋 ,

I apologize for my recent absence; I've been busy with other commitments. It's great to have you back, and I really appreciate you taking the time to work on this PR and resolve the merge conflicts.

> Have you had time to look into this, yet?
> I noticed one of the CI tasks failed. From what I can tell, this seems to be related to permission issues on my end rather than any changes in the PR. 

Since this PR is from a fork, GitHub won't allow the preview package to be published through the workflow, so I'll need to test it manually.

> I'll just assume that the two extra options are fine :slightly_smiling_face:

The options look good to me!

I'll test the PR tomorrow and then proceed with merging it. I'll also review any accompanying documentation changes to ensure everything is consistent.

**Comment by ankur-arch** [comment]
Hey @Dobefu 👋,

I gave the PR a try and still have a few tests left to go. Sorry for the delay—I'll wrap it up on Monday! 😊

**Comment by ankur-arch** [comment]
*Hey there 👋** @Dobefu, here's an update:

1. When I use the `prismaRoot` option with Nuxt layers, it throws the following error when running `npm run dev`:
    Error Screenshot

2. Additionally, Prisma Studio isn't working as expected. It requires specifying the schema path via the `--schema` flag when starting Prisma Studio:
    Schema Path Screenshot

Would it be possible to add me as a collaborator (`ankur-arch`) to your fork so I can commit directly and help resolve these issues?

Thanks in advance! 🙌

**Comment by Dobefu** [comment]
Hi @ankur-arch!

I sure can. I've sent you an invitation to the repo

**Comment by ankur-arch** [comment]
Accepted it!

**Comment by ankur-arch** [comment]
@Dobefu closing this in favor of #71 😄 . 

I'll be back on the 26th to create the docs for this as it introduces quite some changes. Meanwhile, you can checkout the pre-released version here `0.0.0-experimental-2aea052`.

Happy holidays 🫶 !

**Pull request closed without merging**
