### PR TITLE
feat: add layered architecture support

### PR DESCRIPTION
**Pull request by ankur-arch**
- Adds layered architecture(#29)
- Closes https://github.com/prisma/nuxt-prisma/issues/67
- Closes https://github.com/prisma/nuxt-prisma/issues/29

### CODE REVIEW

**Review by husayt — CHANGES_REQUESTED** [review]
we have a problem with windows support. One suggestion would be instead of path to use [pathe](https://unjs.io/packages/pathe)

**Comment by ankur-arch** [comment]
Thanks for the suggestion @husayt, I'm using `pathe` instead of `path`.

**Review by husayt — APPROVED** [review]

**Comment by ankur-arch** [comment]
Hey folks 👋,

This PR is ready to merge! However, there are some associated documentation updates that I’m currently working on and plan to finish by tomorrow.

In the meantime, you can test and use this release by installing: `0.0.0-experimental-2a18f01`.

Thank you all for your suggestions and patience! 🙏

**Comment by husayt** [comment]
@ankur-arch can you also update dependencies please? I am getting all kind of issues during install. latest nuxt is 3.15 now.

**Comment by Kuuzoo** [comment]
> Hey folks 👋,
> 
> This PR is ready to merge! However, there are some associated documentation updates that I’m currently working on and plan to finish by tomorrow.
> 
> In the meantime, you can test and use this release by installing: `0.0.0-experimental-2a18f01`.
> 
> Thank you all for your suggestions and patience! 🙏

Hi @ankur-arch, first of all, thank you!
I've just installed the version via `bun i @prisma/nuxt@0.0.0-experimental-2a18f01`, and added it to my nuxt modules.

But now that I've tried to run dev, I'm stuck in a infinite loop as seen in the following picture. Sadly, I didn't find a way how to get out of there...

Maybe somebody else can give it a shot?
image

**Comment by ankur-arch** [comment]
Hey there @Kuuzoo 👋 ,

Thanks! 

> But now that I've tried to run dev, I'm stuck in a infinite loop as seen in the following picture. Sadly, I didn't find a way how to get out of there...

I've reproduced the issue and will create a follow-up issue for it to investigate further after releasing 1.4.  Currently, we're focused on prioritizing popular package managers such as npm, yarn, and pnpm. I've documented this issue to keep users aware in the docs PR [here](https://github.com/prisma/docs/pull/6557).

> Maybe somebody else can give it a shot?

I always appreciate collaborators!

Also @Dobefu thanks for the immense work 🙏  and @husayt for the suggestion.

**Comment by Kuuzoo** [comment]
> Hey there @Kuuzoo 👋 ,
> 
> Thanks!
> 
> > But now that I've tried to run dev, I'm stuck in a infinite loop as seen in the following picture. Sadly, I didn't find a way how to get out of there...
> 
> I've reproduced the issue and will create a follow-up issue for it to investigate further after releasing 1.4. Currently, we're focused on prioritizing popular package managers such as npm, yarn, and pnpm. I've documented this issue to keep users aware in the docs PR [here](https://github.com/prisma/docs/pull/6557).
> 
> > Maybe somebody else can give it a shot?
> 
> I always appreciate collaborators!
> 
> Also @Dobefu thanks for the immense work 🙏 and @husayt for the suggestion.

Does this issue only happen with bun? or is this with all other package managers like pnpm, yarn, deno, etc?

**Review by jharrell — APPROVED** [review]

**Comment by ankur-arch** [comment]
> Does this issue only happen with bun? or is this with all other package managers like pnpm, yarn

I've tested the code with npm, Yarn, pnpm, and Bun, but I haven't tested it with Deno yet. Since the issue doesn't occur with the supported package managers, I believe this PR is ready to be closed.

That said, I can update the documentation title to something more descriptive, like 'Supported Package Managers,' and include Deno there as well if needed.

**Comment by Kuuzoo** [comment]
> > Does this issue only happen with bun? or is this with all other package managers like pnpm, yarn
> 
> Hey @Kuuzoo ,
> 
> I've tested the code with npm, Yarn, pnpm, and Bun, but I haven't tested it with Deno yet. Since the issue doesn't occur with the supported package managers, I believe this PR is ready to be closed.
> 
> That said, I can update the documentation title to something more descriptive, like 'Supported Package Managers,' and include Deno there as well if needed.

Maybe bun has some seperate order with calling postinstall? Maybe they are trying to call it before 100% finishing the installation of the package, which will cause it to be stuck in a loop.

I've also did a little bit of refactoring and got rid of the own functions to check if prisma is installed, because you now have nypm so we can actually make use of it 🙃
https://github.com/Kuuzoo/nuxt-prisma/commit/4baa33fb1ad2346f88969e873b53efc0efd3dfe8

Should I open a PR about this?

**Comment by ankur-arch** [comment]
> Maybe bun has some seperate order with calling postinstall? Maybe they are trying to call it before 100% finishing the installation of the package, which will cause it to be stuck in a loop.

> I've also did a little bit of refactoring and got rid of the own functions to check if prisma is installed, because you now have nypm so we can actually make use of it 🙃
https://github.com/Kuuzoo/nuxt-prisma/commit/4baa33fb1ad2346f88969e873b53efc0efd3dfe8

> Should I open a PR about this?

@Kuuzoo Please do! Let's carry on the conversation there.

**Comment by Kuuzoo** [comment]
> > Maybe bun has some seperate order with calling postinstall? Maybe they are trying to call it before 100% finishing the installation of the package, which will cause it to be stuck in a loop.
> 
> > I've also did a little bit of refactoring and got rid of the own functions to check if prisma is installed, because you now have nypm so we can actually make use of it 🙃
> > [Kuuzoo@4baa33f](https://github.com/Kuuzoo/nuxt-prisma/commit/4baa33fb1ad2346f88969e873b53efc0efd3dfe8)
> 
> > Should I open a PR about this?
> 
> @Kuuzoo Please do! Let's carry on the conversation there.

Should be open now 👍
https://github.com/prisma/nuxt-prisma/pull/73

**Pull request merged**
