### PR TITLE
fix: replace spawn with execa to fix Windows compatibility

### PR DESCRIPTION
**Pull request by JohanManders**
### Description

This PR replaces the usage of `spawn` with `execa` to resolve compatibility issues on Windows systems.

### Changes Made
- Replaced all occurrences of `spawn` with `execa` in the `installStudio` function.
- Ensured that Prisma Studio runs asynchronously without blocking the execution of the rest of the code.

### Issue
Should fix issues #35 and #13

### CODE REVIEW

**Review by Kuuzoo — APPROVED** [review]

**Comment by BlueBazze** [comment]
It is technically possible that the user does not have npx installed.

Remember seeing this function, havent played with it.
https://devtools.nuxt.com/module/utils-kit#startsubprocess

**Comment by JohanManders** [comment]
> It is technically possible that the user does not have npx installed.
> 
> Remember seeing this function, havent played with it. https://devtools.nuxt.com/module/utils-kit#startsubprocess

The original implementation already relies on npx, as do several other functions within this file, so npx should be available in the environment where this code is running. Given that context, I believe the PR maintains consistency with the existing codebase without introducing additional dependencies.

**Comment by husayt** [comment]
@ankur-arch this also looks like easy fix to another blocker. Will be great to adopt it

**Comment by ankur-arch** [comment]
@husayt I'm currently cleaning up the repo and release process a bit. Will test and merge this soon.

**Review by ankur-arch — APPROVED** [review]

**Comment by ankur-arch** [comment]
Apologies for the delay in merging it. I tested it out and it LGTM!

Thank you for submitting the PR, @JohanManders, really appreciate it 🙌 .

**Pull request merged**
